language: objective-c
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
before_install:
  - gem install xcpretty
script:
  - rake "clean['TwitterClient-iOS RichTextEditor TwitterClient-Mac']"
  - rake "build['TwitterClient-iOS RichTextEditor TwitterClient-Mac']"
   
